service: <%= projectName %>

frameworkVersion: ">=1.28.0 <2.0.0"

package:
 exclude:
   - ./**
 include:
   - ./bin/**

custom: ${file(./configs/config.${self:provider.stage}.json)}

provider:
  name: aws
  cfLogs: true
  runtime: go1.x
  role: ${opt:role, self:custom.role}
  stage: ${opt:stage, 'dev'}
  region: ${self:custom.region}
  memorySize: ${self:custom.memory} 
  stackTags: ${self:custom.tags}
  vpc:
    subnetIds: ${self:custom.vpc.subnetIds}
    securityGroupIds: ${self:custom.vpc.securityGroupIds}
    
plugins:
  - serverless-sam

functions:
### yeoman hook ###
## Don't touch this comment, the subgenerator needs it'

## Uncomment for dev purpose only.
## Re-comment it before deploy !!
#plugins:
#  - serverless-offline
